import QtQuick
import Quickshell.Io

Item {
    id: root

    // Fallback default values
    property color background: "#181825"
    property color foreground: "#cdd6f4"
    property color muted: "#585b70"
    property color accent1: "#81c8be"
    property color accent2: "#8caaee"
    property color accent3: "#a6d189"
    property color accent4: "#e5c890"
    property color accent5: "#ef9f76"
    property color accent6: "#e78284"
    property color accent7: "#ca9ee6"

    property color barColor: "#181825"
    property real barOpacity: 0.85

    property string fontFamily: "JetBrainsMono Nerd Font"
    property int fontSize: 13

    // Dynamically watch the JSON file generated by theme-switch.nix
    FileView {
        id: themeFile
        path: "/home/p/.cache/theme-colors.json"
        watchChanges: true
        
        // explicitly tell Quickshell to fetch the new data
        onFileChanged: reload()

        // onLoaded takes no arguments, so we read text() directly
        onLoaded: {
            let dataString = themeFile.text();
            if (!dataString) return;
            
            try {
                let theme = JSON.parse(dataString);
                root.background = theme.background;
                root.foreground = theme.foreground;
                root.muted = theme.muted;
                root.accent1 = theme.accent1;
                root.accent2 = theme.accent2;
                root.accent3 = theme.accent3;
                root.accent4 = theme.accent4;
                root.accent5 = theme.accent5;
                root.accent6 = theme.accent6;
                root.accent7 = theme.accent7;
                root.barColor = theme.barColor;
                root.barOpacity = theme.barOpacity;
                root.fontFamily = theme.font;
                root.fontSize = theme.fontSize;
            } catch (e) {
                console.log("Failed to parse theme JSON: " + e);
            }
        }
    }
}
