import QtQuick
import Quickshell.Io

Item {
    id: root

    // Fallback default values
    property color colBg: "#181825"
    property color colFg: "#cdd6f4"
    property color colMuted: "#585b70"
    property color colBlue: "#8caaee"
    property color colCyan: "#81c8be"
    property color colGreen: "#a6d189"
    property color colYellow: "#e5c890"
    property color colOrange: "#ef9f76"
    property color colRed: "#e78284"
    property color colPurple: "#ca9ee6"

    property color barColor: "#181825"
    property real barOpacity: 0.85

    property string fontFamily: "JetBrainsMono Nerd Font"
    property int fontSize: 13

    // Dynamically watch the JSON file generated by theme-switch.nix
    FileView {
        id: themeFile
        path: "/home/p/.cache/theme-colors.json"
        watchChanges: true
        
        // explicitly tell Quickshell to fetch the new data
        onFileChanged: reload()

        // onLoaded takes no arguments, so we read text() directly
        onLoaded: {
            let dataString = themeFile.text();
            if (!dataString) return;
            
            try {
                let theme = JSON.parse(dataString);
                root.colBg = theme.bg;
                root.colFg = theme.fg;
                root.colMuted = theme.muted;
                root.colBlue = theme.blue;
                root.colCyan = theme.cyan;
                root.colGreen = theme.green;
                root.colYellow = theme.yellow;
                root.colOrange = theme.orange;
                root.colRed = theme.red;
                root.colPurple = theme.purple;
                root.barColor = theme.barColor;
                root.barOpacity = theme.barOpacity;
                root.fontFamily = theme.font;
                root.fontSize = theme.fontSize;
            } catch (e) {
                console.log("Failed to parse theme JSON: " + e);
            }
        }
    }
}
