# rebind volume control
unbindsym --locked XF86AudioRaiseVolume
bindsym --locked XF86AudioRaiseVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ --limit 1.0

unbindsym --locked XF86AudioLowerVolume
bindsym --locked XF86AudioLowerVolume exec wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

# for mute light related issues; see ~/.dotfiles/sway/.local/bin/mute-led-daemon.sh
unbindsym --locked XF86AudioMute
bindsym --locked XF86AudioMute exec wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

unbindsym --locked XF86AudioMicMute
bindsym --locked XF86AudioMicMute exec wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# --- Media Playback Controls ---
# (No unbindsym needed here because these are not bound by default)
bindsym --locked XF86AudioPlay exec ~/.ndots/config/sway/scripts/media-control.sh play-pause
bindsym --locked XF86AudioNext exec ~/.ndots/config/sway/scripts/media-control.sh next
bindsym --locked XF86AudioPrev exec ~/.ndots/config/sway/scripts/media-control.sh previous

# this script cycles through all mpd instances
bindsym F8 exec ~/.ndots/config/sway/scripts/cycle-media.sh
