# SwayFX settings
# exec autotiling
# # fix for mute led light
# exec ~/.local/bin/mute-led-daemon.sh
# animation_duration_ms 250
exec autotiling
exec qs
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP SWAYSOCK
exec systemctl --user start graphical-session.target
output * bg ~/Pictures/Wallpapers/wallpaper.jpg fill
for_window [class="libreoffice-writer" title="TexMaths.*"] floating enable

# blur_xray enables wallpaper blurring without blurring windows below
blur_xray enable
#blur_passes 4
#blur_radius 4
blur enable
blur_passes 3
blur_radius 3
blur_noise 0
layer_effects "notifications" {
    blur enable
    blur_ignore_transparent enable
}
# blur_noise <float value 0 - 1>
# blur_brightness <float value 0 - 2>
# blur_contrast <float value 0 - 2>
# blur_saturation <float value 0 - 2>
client.focused          #ffffff88 #ffffff88 #000000ff #ffffff88 #ffffff88
client.focused_inactive #00000000 #00000000 #ffffff88 #00000000 #00000000
client.unfocused        #00000000 #00000000 #ffffff88 #00000000 #00000000
default_border normal
#default_border pixel 2
#default_floating_border pixel 2
# Window corners can be rounded in SwayFX
# corner_radius can be any number of pixels
 # corner_radius 0
gaps inner 5

# SwayFX also features window drop shadows, which, of course, can be enabled at any time
shadows disable
shadows_on_csd disable

# You can also offset the shadow's position, make unfocused windows have different shadows, give shadows a nondefault color, and blur shadows
# shadow_inactive_color #0000007F
# shadow_offset <x offset> <y offset>
# shadow_blur_radius <integer value 0 - 99>
# shadow_color <hex color with alpha>

# Dimming
# default_dim_inactive <float value 0.0 - 1.0>
# for_window [CRITERIA_HERE] dim_inactive <float value 0.0 - 1.0>
# dim_inactive_colors.unfocused <hex color>
# dim_inactive_colors.urgent <hex color> 
# exec systemctl --user start xdg-desktop-portal
# exec_always ~/.config/sway/scripts/launch_waybar.sh
